# Generated by Django 3.2.5 on 2021-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210825_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='CoverPage',
            field=models.ImageField(null=True, upload_to='Covers/'),
        ),
    ]
